spring.application.name=${SPRING_APPLICATION_NAME:fire-backend-service}
spring.profiles.active=${SPRING_PROFILE:dev}
server.port=${BACKEND_PORT:8181}
logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.pl.edu.agh.kis.firebackend=${LOG_LEVEL_APP:INFO}
logging.file.name=${LOG_FILE_NAME:./logs/application.log}
logging.pattern.console=${LOG_PATTERN:%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%level] %logger{36} - %msg%n}
logging.pattern.file=${LOG_PATTERN:%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} [%level] %logger{36} - %msg%n}

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,mappings
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq-service}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}